### PR TITLE
Things I noticed

### PR DESCRIPTION
**Pull request by RusteyBucket**
Still haven't figured out where to squash commits in the current branch, oh well, the last one is relevant as I just went through and auto-reformatted, did a minor change in the README and added myself in the mod.lua file

### CODE REVIEW

**Comment by RusteyBucket** [comment]
I noticed that the list of transport modes doesn't seem to line up with testing...

Here my current list (still completing, in brackets are the patterns observed so far, outside the values before my testing, if they're correct)

-- api.engine.getComponent(line_id, api.type.ComponentType.LINE)
-- vehicleInfo = {
--    transportModes = {
--      [1]  = 0,
--      [2]  = 0,
--      [3]  = 0,
--      [4]  = 0, ROAD (BUS)
--      [5]  = 0,
--      [6]  = 0,  (STEAM_TRAM/HORSE_TRAM)
--      [7]  = 0, TRAM (ELECTRIC_TRAM)
--      [8]  = 0, ELECTRIC_TRAM (STEAM_TRAIN)
--      [9]  = 0, RAIL
--      [10] = 0, AIR?
--      [11] = 0, WATER_LARGE (WATER_LARGE)
--      [12] = 0, AIR
--      [13] = 0, WATER_SMALL (WATER_SMALL)
--      [14] = 0,
--      [15] = 0,
--      [16] = 0,
--    },

**Comment by RusteyBucket** [comment]
I found some more:

-- api.engine.getComponent(line_id, api.type.ComponentType.LINE)
-- vehicleInfo = {
--    transportModes = {
--      [1]  = 0,
--      [2]  = 0,
--      [3]  = 0,
--      [4]  = 0, ROAD (BUS)
--      [5]  = 0,  (TRUCK)
--      [6]  = 0,  (STEAM_TRAM/HORSE_TRAM PAX and CARGO)
--      [7]  = 0, TRAM (ELECTRIC_TRAM PAX and CARGO)
--      [8]  = 0, ELECTRIC_TRAM (STEAM_TRAIN)
--      [9]  = 0, RAIL (ELECTRIC_TRAIN)
--      [10] = 0, AIR?
--      [11] = 0, WATER_LARGE (WATER_LARGE)
--      [12] = 0, AIR (PLANE_SMALL_PAX)
--      [13] = 0, WATER_SMALL (WATER_SMALL)
--      [14] = 0,
--      [15] = 0,
--      [16] = 0,
--    },

**Comment by RusteyBucket** [comment]
I now suspect it might be this list here https://transportfever2.com/wiki/api/modules/api.type.html#enum.TransportMode +1 because lua starts counting at 1

**Comment by RusteyBucket** [comment]
I Filled the expected values in with the confirmed values in the brackets:

-- api.engine.getComponent(line_id, api.type.ComponentType.LINE)
-- vehicleInfo = {
--    transportModes = {
--      [1]  = 0, PERSON
--      [2]  = 0, CARGO
--      [3]  = 0, CAR
--      [4]  = 0, BUS (BUS)
--      [5]  = 0, TRUCK (TRUCK)
--      [6]  = 0, TRAM (STEAM_TRAM/HORSE_TRAM PAX and CARGO)
--      [7]  = 0, ELECTRIC_TRAM (ELECTRIC_TRAM PAX and CARGO)
--      [8]  = 0, TRAIN (STEAM_TRAIN)
--      [9]  = 0, ELECTRIC_TRAIN (ELECTRIC_TRAIN)
--      [10] = 0, AIRCRAFT
--      [11] = 0, SHIP (WATER_LARGE)
--      [12] = 0, SMALL_AIRCRAFT (PLANE_SMALL_PAX)
--      [13] = 0, SMALL:SHIP (WATER_SMALL)
--      [14] = 0,
--      [15] = 0,
--      [16] = 0,
--    },

**Comment by TommyC81** [comment]
Thanks for this! I'm manually transposing the information to the main branch.

To move things forward a bit more efficiently, I suggest that you use the main branch as the basis and start from scratch with a fresh pull request (deleting this branch). It's not possible to merge this due to significant differences. Note that I've aligned things slightly differently in the main branch, in particular with regards to logging/debugging. As the changes you proposed were quite fundamental, I took some time to improve the logging/debugging functionality but it is not compatible with this branch.

With fresh PR based on the current main branch, I'll be able to merge quicker and with no/less manual work. Appreciate your help!

**Comment by RusteyBucket** [comment]
> Thanks for this! I'm manually transposing the information to the main branch.
> 
> 
> 
> To move things forward a bit more efficiently, I suggest that you use the main branch as the basis and start from scratch with a fresh pull request (deleting this branch). It's not possible to merge this due to significant differences. Note that I've aligned things slightly differently in the main branch, in particular with regards to logging/debugging. As the changes you proposed were quite fundamental, I took some time to improve the logging/debugging functionality but it is not compatible with this branch.
> 
> 
> 
> With fresh PR based on the current main branch, I'll be able to merge quicker and with no/less manual work. Appreciate your help!

Guess I'll restart from scratch, I thought I managed to merge but apparently not...

**Comment by TommyC81** [comment]
You can see in the pull request itself if it can be merged or whether it
has conflicts that need to be resolved prior.

A fair chunk of the suggested changes have been incorporated into the main
code base already, so you won't be starting from scratch per se. It's good
practice to regularly rebase any work you're doing on the main code base -
this allows you to resolve conflicts as you go and align things to be ready
for an easy merge into main.

Having said that, if you want to develop in a different direction, perhaps
for personal needs or for a different idea, then it is of course possible
to just work on your own code base (fork) and cherry pick commits from the
main code base that you deem useful.

I hope this helps. Thanks again for your assistance this far!

**Comment by RusteyBucket** [comment]
I actually had the check mark when creating the pull request and I now just nuked my end and reforked because it pissed me off that auto merging wasn't possible anymore

**Comment by TommyC81** [comment]
I have to say that the commit history was starting to get very messy, some
changes seemed reverted in later commits. I'm actually not entirely sure
what was going on.

Anyway, all good. You can create several different branches yourself and
try to split improvements up into sensible parts, and submit separate and
smaller PRs as you go. You can then merge in commits between branches. It
all depends on the work flow and what you have in mind.

Either way, make sure to fetch and merge from main regularly to stay up to
date.

**Pull request closed without merging**
