### PR TITLE
Figured 'em out, boss

### PR DESCRIPTION
**Pull request by RusteyBucket**

### CODE REVIEW

**Comment by RusteyBucket** [comment]
Sorry, got on the enter key too early; I made a map with basically everything you could need and figured out the Materials in tedious sampling... though hard coding them in shouldn't be advisable since mods will muck that up quick, fast and in a hurry...

**Comment by RusteyBucket** [comment]
Figured those TODOS would be a boost to usability

**Comment by RusteyBucket** [comment]
Sorry to flood you with commits, I only now realized that I should've worked in a separate branch and squashed those commits into the main for submitting...

**Comment by TommyC81** [comment]
Thanks for this, I've squashed and cherry-picked the latest commits. They've been merged into main.

Please kill your local branch and start a completely clean one from main - this one is getting unnecessarily messy. You can delete this branch within Github Desktop or here on Github (make sure to delete the upstream branch copy as well), then simply continue working from the main branch - creating PR with differences from the main branch only. I hope this makes sense. It's easier than it sounds and makes it much easier to track and merge items, cleaner as well.

Either way, I appreciate this and it seems that many people are looking forward to further changes/improvements! You've certainly given me some inspiration to continue working on it - fresh eyes! :-)

**Comment by RusteyBucket** [comment]
> Thanks for this, I've squashed and cherry-picked the latest commits. They've been merged into main.
> 
> Please kill your local branch and start a completely clean one from main - this one is getting unnecessarily messy. You can delete this branch within Github Desktop or here on Github (make sure to delete the upstream branch copy as well), then simply continue working from the main branch - creating PR with differences from the main branch only. I hope this makes sense. It's easier than it sounds and makes it much easier to track and merge items, cleaner as well.
> 
> Either way, I appreciate this and it seems that many people are looking forward to further changes/improvements! You've certainly given me some inspiration to continue working on it - fresh eyes! :-)

Exactly what I planned on doing, now that I figured that part of git out... took me long enough and I hope I get it right

**Comment by TommyC81** [comment]
Fantastic! Keep it coming!

**Pull request closed without merging**
